---
# THIS IS NOT A TEMPLATE.
# This is just for testing the repo itself.
# This calls the reusable workflow from its local file path.
name: Docker Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/linters/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - ".github/linters/**"

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  call-qemu-docker-build:
    name: Call _QEMU_ Docker Build

    uses: ./.github/workflows/reusable-docker-build.yaml

    with:
      dockerhub-enable: false
      ghcr-enable: true

      image-names: |
        ghcr.io/bretfisher/docker-build-workflow-qemu

      platforms: linux/amd64, linux/arm64

  call-native-docker-build:
    name: Call _Native_ Docker Build

    uses: ./.github/workflows/reusable-docker-build-native.yaml

    with:
      dockerhub-enable: false
      ghcr-enable: true

      image-names: |
        ghcr.io/bretfisher/docker-build-workflow

      platforms: '["linux/amd64", "linux/arm64"]'
